sudo: false
language: java
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.m2"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_865dee0081bc_key -iv $encrypted_865dee0081bc_iv -in
    kafka-pubsub-emulator_svc_acct.json.enc -out kafka-pubsub-emulator_svc_acct.json -d
- gcloud version || echo "gcloud not installed"
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file kafka-pubsub-emulator_svc_acct.json
- gcloud config set project kafka-pubsub-emulator
script:
- mvn -B clean cobertura:cobertura package
after_success:
# Upload coverage
- bash <(curl -s https://codecov.io/bash)
# Upload JAR to GCS
- gsutil -h "Cache-Control: no-cache, no-store, must-revalidate" cp -a public-read -v
    `ls target/kafka-pubsub-emulator*.jar` gs://kafka-pubsub-emulator/
